model_name: hf-internal-testing/tiny-random-bert
device: cpu
max_length: 128
batch_size: 16
lr: 5e-4
weight_decay: 0.0
num_epochs: 1
warmup_steps: 0

alpha_cls: 1.0
alpha_vad: 1.0
alpha_sinkhorn: 0.4
alpha_mass: 0.1
sinkhorn_epsilon: 0.1
sinkhorn_iters: 30
ot_mode: unbalanced_divergence
ot_cost: vad
ot_reg_m: 0.5


threshold: 0.5
use_silver: true
silver_weight: 1.0
seed: 13
grad_clip: 2.0
save_dir: checkpoints_smoke


data_path: /tmp/icj_train_smoke.jsonl
eval_path: /tmp/icj_dev_smoke.jsonl

lexicon_path: data/NRC-Emotion-Lexicon
vad_lexicon_path: data/NRC-VAD-Lexicon-v2.1
lexicon_vad_scale: null
word_vad_scale: null
lexicon_stopwords_file: data/stopwords_legal_en.txt
lexicon_negation_window: 3
lexicon_negators: ["not", "no", "never", "without", "neither", "nor", "cannot", "can't", "dont", "don't", "won't"]
label_vad_scale: auto
count_pred_scale: density
semantic_calibration: true
semantic_calibration_allow_seed: false
semantic_lexicon_strength_per_1k: 3.0
semantic_min_signal_per_1k_words: 0.2
semantic_zero_low_signal: true
compare_drop_low_signal: true
token_emotional_vocab: lexicon
token_stopwords_file: data/stopwords_legal_en_token_ot.txt
token_include_english_stopwords: false
token_vad_imputed_weight: 0.35
token_vad_imputed_path: data/derived/token_vad_imputed.json
token_term_weights_path: data/derived/token_term_weights.json
token_term_weight_power: 2.0
token_term_weight_min: 0.0
token_term_weight_max: 1.0
token_term_weight_mix: 1.0
token_term_weight_default: 1.0
